### ISSUE TITLE
registration failed or deregistering

### ISSUE THREAD

**Issue by BRIDGE-AI** [tayler6000/pyVoIP#242]
Hello,

I'm testing on v2.0.0a5.

It looks that cannot register and I can see the text 'Deregistering' on the log.
Can you check this out?

Here's the log below.

```
계속하려면 엔터 혹은 명령을 입력하십시오
-->python t_ex1_ann.py
SENT:
REGISTER sip:211.233.26.247:5060 SIP/2.0

Headers:
Via: [{'type': 'SIP/2.0/UDP', 'address': ('0.0.0.0', 5060), 'branch': 'z9hG4bK6e8882e5a2184ba4abe5ca7dd'}]
From: {'raw': '<sip:07076830783@211.233.26.247>;tag=998e83d8', 'tag': '998e83d8', 'uri': 'sip:07076830783@211.233.26.247', 'uri-type': 'sip', 'user': '07076830783', 'password': '', 'display-name': '', 'host': '211.233.26.247', 'port': 5060}
To: {'raw': '<sip:07076830783@211.233.26.247>', 'tag': '', 'uri': 'sip:07076830783@211.233.26.247', 'uri-type': 'sip', 'user': '07076830783', 'password': '', 'display-name': '', 'host': '211.233.26.247', 'port': 5060}
Call-ID: 6b86b273ff34fce19d6b804eff5a3f57@0.0.0.0:5060
CSeq: {'check': 1, 'method': 'REGISTER'}
Contact: {'raw': '<sip:07076830783@0.0.0.0;transport=UDP>;+sip.instance="<urn:uuid:952688D1-D96F-4DEE-B285-52391C59367B>"', 'tag': '', 'uri': 'sip:07076830783@0.0.0.0', 'uri-type': 'sip', 'user': '07076830783', 'password': '', 'display-name': '', 'host': '0.0.0.0', 'port': 5060}
Allow: ['INVITE', 'ACK', 'BYE', 'CANCEL', 'OPTIONS', 'NOTIFY', 'REGISTER', 'MESSAGE', 'SUBSCRIBE', 'REFER']
Max-Forwards: 70
Allow-Events: org.3gpp.nwinitdereg
User-Agent: pyVoIP 2.0.0a5
Expires: 120
Content-Length: 0

Body:
content: None

Raw:
b'REGISTER sip:211.233.26.247:5060 SIP/2.0\r\nVia: SIP/2.0/UDP 0.0.0.0:5060;branch=z9hG4bK6e8882e5a2184ba4abe5ca7dd\r\nFrom: <sip:07076830783@211.233.26.247>;tag=998e83d8\r\nTo: <sip:07076830783@211.233.26.247>\r\nCall-ID: 6b86b273ff34fce19d6b804eff5a3f57@0.0.0.0:5060\r\nCSeq: 1 REGISTER\r\nContact: <sip:07076830783@0.0.0.0;transport=UDP>;+sip.instance="<urn:uuid:952688D1-D96F-4DEE-B285-52391C59367B>"\r\nAllow: INVITE, ACK, BYE, CANCEL, OPTIONS, NOTIFY, REGISTER, MESSAGE, SUBSCRIBE, REFER\r\nMax-Forwards: 70\r\nAllow-Events: org.3gpp.nwinitdereg\r\nUser-Agent: pyVoIP 2.0.0a5\r\nExpires: 120\r\nContent-Length: 0\r\n\r\n'


Received UDP Message:
SIP/2.0 401 Unauthorized

Headers:
Via: [{'type': 'SIP/2.0/UDP', 'address': ('0.0.0.0', 5060), 'branch': 'z9hG4bK6e8882e5a2184ba4abe5ca7dd', 'received': '43.202.127.199'}]
From: {'raw': '<sip:07076830783@211.233.26.247>;tag=998e83d8', 'tag': '998e83d8', 'uri': 'sip:07076830783@211.233.26.247', 'uri-type': 'sip', 'user': '07076830783', 'password': '', 'display-name': '', 'host': '211.233.26.247', 'port': 5060}
To: {'raw': '<sip:07076830783@211.233.26.247>;tag=ebcb6c0114297d73a48fab2b598eb87c', 'tag': 'ebcb6c0114297d73a48fab2b598eb87c', 'uri': 'sip:07076830783@211.233.26.247', 'uri-type': 'sip', 'user': '07076830783', 'password': '', 'display-name': '', 'host': '211.233.26.247', 'port': 5060}
Call-ID: 6b86b273ff34fce19d6b804eff5a3f57@0.0.0.0:5060
CSeq: {'check': 1, 'method': 'REGISTER'}
Contact: {'raw': '<sip:07076830783@0.0.0.0;transport=UDP>;+sip.instance="<urn:uuid:952688D1-D96F-4DEE-B285-52391C59367B>"', 'tag': '', 'uri': 'sip:07076830783@0.0.0.0', 'uri-type': 'sip', 'user': '07076830783', 'password': '', 'display-name': '', 'host': '0.0.0.0', 'port': 5060}
WWW-Authenticate: {'header': 'WWW-Authenticate', 'method': 'Digest', 'realm': 'sip1.1stnet.co.kr', 'nonce': '6be5f220592a70d7f6bb463470a9509c', 'stale': 'true', 'algorithm': 'MD5'}
Content-Length: 0

Body:
content: None

Raw:
b'SIP/2.0 401 Unauthorized\r\nVia: SIP/2.0/UDP 0.0.0.0:5060;branch=z9hG4bK6e8882e5a2184ba4abe5ca7dd;received=43.202.127.199\r\nFrom: <sip:07076830783@211.233.26.247>;tag=998e83d8\r\nTo: <sip:07076830783@211.233.26.247>;tag=ebcb6c0114297d73a48fab2b598eb87c\r\nCall-ID: 6b86b273ff34fce19d6b804eff5a3f57@0.0.0.0:5060\r\nCSeq: 1 REGISTER\r\nContact: <sip:07076830783@0.0.0.0;transport=UDP>;+sip.instance="<urn:uuid:952688D1-D96F-4DEE-B285-52391C59367B>"\r\nWWW-Authenticate: Digest realm="sip1.1stnet.co.kr", nonce="6be5f220592a70d7f6bb463470a9509c", stale=true, algorithm=MD5\r\nContent-Length: 0\r\n\r\n'
New Connection Started
Deregistering <pyVoIP.networking.sock.VoIPConnection object at 0x7f117edd3880>
self.conns=[<pyVoIP.networking.sock.VoIPConnection object at 0x7f117edd3880>]
listening: [["6b86b273ff34fce19d6b804eff5a3f57@0.0.0.0:5060", "998e83d8", "ebcb6c0114297d73a48fab2b598eb87c", 0]]

msgs: []


SENT:
REGISTER sip:211.233.26.247:5060 SIP/2.0

Headers:
Via: [{'type': 'SIP/2.0/UDP', 'address': ('0.0.0.0', 5060), 'branch': 'z9hG4bK5517b6f6dafc43e98e3b3779f'}]
From: {'raw': '<sip:07076830783@211.233.26.247>;tag=998e83d8', 'tag': '998e83d8', 'uri': 'sip:07076830783@211.233.26.247', 'uri-type': 'sip', 'user': '07076830783', 'password': '', 'display-name': '', 'host': '211.233.26.247', 'port': 5060}
To: {'raw': '<sip:07076830783@211.233.26.247>', 'tag': '', 'uri': 'sip:07076830783@211.233.26.247', 'uri-type': 'sip', 'user': '07076830783', 'password': '', 'display-name': '', 'host': '211.233.26.247', 'port': 5060}
Call-ID: 6b86b273ff34fce19d6b804eff5a3f57@0.0.0.0:5060
CSeq: {'check': 2, 'method': 'REGISTER'}
Contact: {'raw': '<sip:07076830783@0.0.0.0;transport=UDP>;+sip.instance="<urn:uuid:952688D1-D96F-4DEE-B285-52391C59367B>"', 'tag': '', 'uri': 'sip:07076830783@0.0.0.0', 'uri-type': 'sip', 'user': '07076830783', 'password': '', 'display-name': '', 'host': '0.0.0.0', 'port': 5060}
Allow: ['INVITE', 'ACK', 'BYE', 'CANCEL', 'OPTIONS', 'NOTIFY', 'REGISTER', 'MESSAGE', 'SUBSCRIBE', 'REFER']
Max-Forwards: 70
Allow-Events: org.3gpp.nwinitdereg
User-Agent: pyVoIP 2.0.0a5
Expires: 120
Authorization: {'header': 'Authorization', 'method': 'Digest', 'username': '07076830783', 'realm': 'sip1.1stnet.co.kr', 'nonce': '6be5f220592a70d7f6bb463470a9509c', 'uri': 'sip:211.233.26.247;transport=UDP', 'response': '9a4ab39f6ac75096ff4afb2ab456b9c2', 'algorithm': 'md5'}
Content-Length: 0

Body:
content: None

Raw:
b'REGISTER sip:211.233.26.247:5060 SIP/2.0\r\nVia: SIP/2.0/UDP 0.0.0.0:5060;branch=z9hG4bK5517b6f6dafc43e98e3b3779f\r\nFrom: <sip:07076830783@211.233.26.247>;tag=998e83d8\r\nTo: <sip:07076830783@211.233.26.247>\r\nCall-ID: 6b86b273ff34fce19d6b804eff5a3f57@0.0.0.0:5060\r\nCSeq: 2 REGISTER\r\nContact: <sip:07076830783@0.0.0.0;transport=UDP>;+sip.instance="<urn:uuid:952688D1-D96F-4DEE-B285-52391C59367B>"\r\nAllow: INVITE, ACK, BYE, CANCEL, OPTIONS, NOTIFY, REGISTER, MESSAGE, SUBSCRIBE, REFER\r\nMax-Forwards: 70\r\nAllow-Events: org.3gpp.nwinitdereg\r\nUser-Agent: pyVoIP 2.0.0a5\r\nExpires: 120\r\nAuthorization: Digest username="07076830783",realm="sip1.1stnet.co.kr",nonce="6be5f220592a70d7f6bb463470a9509c",uri="sip:211.233.26.247;transport=UDP",response="9a4ab39f6ac75096ff4afb2ab456b9c2",algorithm=md5\r\nContent-Length: 0\r\n\r\n'


Received UDP Message:
SIP/2.0 200 OK

Headers:
Via: [{'type': 'SIP/2.0/UDP', 'address': ('0.0.0.0', 5060), 'branch': 'z9hG4bK5517b6f6dafc43e98e3b3779f', 'received': '43.202.127.199'}]
From: {'raw': '<sip:07076830783@211.233.26.247>;tag=998e83d8', 'tag': '998e83d8', 'uri': 'sip:07076830783@211.233.26.247', 'uri-type': 'sip', 'user': '07076830783', 'password': '', 'display-name': '', 'host': '211.233.26.247', 'port': 5060}
To: {'raw': '<sip:07076830783@211.233.26.247>;tag=ebcb6c0114297d73a48fab2b598eb87c', 'tag': 'ebcb6c0114297d73a48fab2b598eb87c', 'uri': 'sip:07076830783@211.233.26.247', 'uri-type': 'sip', 'user': '07076830783', 'password': '', 'display-name': '', 'host': '211.233.26.247', 'port': 5060}
Call-ID: 6b86b273ff34fce19d6b804eff5a3f57@0.0.0.0:5060
CSeq: {'check': 2, 'method': 'REGISTER'}
Contact: {'raw': '<sip:07076830783@0.0.0.0:uuid:95268UDP;transport=UDP>;expires=120', 'tag': '', 'uri': 'sip:07076830783@0.0.0.0', 'uri-type': 'sip', 'user': '07076830783', 'password': '', 'display-name': '', 'host': '0.0.0.0', 'port': 5060}
Expires: 120
Content-Length: 0

Body:
content: None

Raw:
b'SIP/2.0 200 OK\r\nVia: SIP/2.0/UDP 0.0.0.0:5060;branch=z9hG4bK5517b6f6dafc43e98e3b3779f;received=43.202.127.199\r\nFrom: <sip:07076830783@211.233.26.247>;tag=998e83d8\r\nTo: <sip:07076830783@211.233.26.247>;tag=ebcb6c0114297d73a48fab2b598eb87c\r\nCall-ID: 6b86b273ff34fce19d6b804eff5a3f57@0.0.0.0:5060\r\nCSeq: 2 REGISTER\r\nContact: <sip:07076830783@0.0.0.0:uuid:95268UDP;transport=UDP>;expires=120\r\nExpires: 120\r\nContent-Length: 0\r\n\r\n'
New Connection Started
Deregistering <pyVoIP.networking.sock.VoIPConnection object at 0x7f117edd3bb0>
self.conns=[None, <pyVoIP.networking.sock.VoIPConnection object at 0x7f117edd3bb0>]
listening: [["6b86b273ff34fce19d6b804eff5a3f57@0.0.0.0:5060", "998e83d8", "ebcb6c0114297d73a48fab2b598eb87c", 1]]

msgs: []


New register thread
```

Thank you!

**Comment by BRIDGE-AI** [comment]
First of all, I'm sorry.

I think I misjudged the registration status just by looking at the word 'Deregistering'.
When I looked into the internal code, I found that 'Deregistering' was performed even when OK was received after REGISTER using a password.
My code couldn't answer the call on v2.0.0a5.
Since it didn't respond properly to calls after running it, I naturally assumed it wasn't registered properly.
Sorry, again.

I'm trying to find why this cannot answer the call.

**Comment by BRIDGE-AI** [comment]
I got this logs right after I'm calling.

```
Received UDP Message:
INVITE sip:07076830783@0.0.0.0:5060;user=phone SIP/2.0

Headers:
  Via: [{'type': 'SIP/2.0/UDP', 'address': ('211.233.26.247', 5060), 'branch': 'z9hG4bK7be83679_102'}, {'type': 'SIP/2.0/UDP', 'address': ('3.39.185.227', 5060), 'branch': 'z9hG4bK7be83679'}]
  From: {'raw': '<sip:01058547137@211.233.26.247>;tag=813f320c096bd720c51eae29bd422c17', 'tag': '813f320c096bd720c51eae29bd422c17', 'uri': 'sip:01058547137@211.233.26.247', 'uri-type': 'sip', 'user': '01058547137', 'password': '', 'display-name': '', 'host': '211.233.26.247', 'port': 5060}
  To: {'raw': '<sip:07076830783@0.0.0.0>', 'tag': '', 'uri': 'sip:07076830783@0.0.0.0', 'uri-type': 'sip', 'user': '07076830783', 'password': '', 'display-name': '', 'host': '0.0.0.0', 'port': 5060}
  Record-Route: <sip:211.233.26.247;lr>
  Call-ID: 211.233.26.247_02a5a36365861953571211286c78be84@3.39.185.227
  CSeq: {'check': 102, 'method': 'INVITE'}
  Contact: {'raw': '<sip:01058547137@211.233.26.247:5060;user=phone>', 'tag': '', 'uri': 'sip:01058547137@211.233.26.247:5060', 'uri-type': 'sip', 'user': '01058547137', 'password': '', 'display-name': '', 'host': '211.233.26.247', 'port': 5060}
  Max-Forwards: 69
  Content-Type: application/sdp
  Content-Length: 200

Body:
o: {'username': 'root', 'id': '446059229', 'version': '446059229', 'network_type': 'IN', 'address_type': 'IP4', 'address': '211.233.26.249'}
s: GP ARS 1.0
c: [{'network_type': 'IN', 'address_type': 'IP4', 'address': '211.233.26.249', 'ttl': None, 'address_count': 1}]
t: {'start': '0', 'stop': '0'}
m: [{'type': 'audio', 'port': 20656, 'port_count': 1, 'protocol': <RTPProtocol.AVP: 'RTP/AVP'>, 'methods': ['0', '8'], 'attributes': {'0': {'rtpmap': {'id': '0', 'name': 'PCMU', 'frequency': '8000', 'encoding': None}}, '8': {'rtpmap': {'id': '8', 'name': 'PCMA', 'frequency': '8000', 'encoding': None}}}}]
a: {'maxptime': '150', 'transmit_type': <TransmitType.SENDRECV: 'sendrecv'>}

Raw:
b'INVITE sip:07076830783@0.0.0.0:5060;user=phone SIP/2.0\r\nVia: SIP/2.0/UDP 211.233.26.247:5060;branch=z9hG4bK7be83679_102\r\nVia: SIP/2.0/UDP 3.39.185.227:5060;branch=z9hG4bK7be83679\r\nFrom: <sip:01058547137@211.233.26.247>;tag=813f320c096bd720c51eae29bd422c17\r\nTo: <sip:07076830783@0.0.0.0>\r\nRecord-Route: <sip:211.233.26.247;lr>\r\nCall-ID: 211.233.26.247_02a5a36365861953571211286c78be84@3.39.185.227\r\nCSeq: 102 INVITE\r\nContact: <sip:01058547137@211.233.26.247:5060;user=phone>\r\nMax-Forwards: 69\r\nContent-Type: application/sdp\r\nContent-Length: 200\r\n\r\nv=0\r\no=root 446059229 446059229 IN IP4 211.233.26.249\r\ns=GP ARS 1.0\r\nc=IN IP4 211.233.26.249\r\nt=0 0\r\nm=audio 20656 RTP/AVP 0 8\r\na=rtpmap:0 PCMU/8000\r\na=rtpmap:8 PCMA/8000\r\na=maxptime:150\r\na=sendrecv\r\n'
New Connection Started
```

But, no answers on the call at all.
And there are no more logs until a relay message appears saying that connection cannot be made.
